import Head from 'next/head';
import Services from '../components/Services';
import css from '../styles/Home.module.css';
import { client } from '../lib/client';
import Menu from '../components/Menu';
import MainCarousel from '../components/Carousel/MainCarousel';
import { Login } from './login';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import Category from '../components/Category';
import Layout from '../components/Layout/Layout';
import SetTheme from '../components/SetTheme';
import Banner from '../components/Banner/Banner';
import FAQ from '../components/FAQ';
import Facebook from '../components/Facebook';

const Home = ({ pizzas, categories, hamburgers, teas, drinks, asianFoods }) => {
  const router = useRouter();

  return (
    <Layout>
      <div className={`${css.container} dark:bg-gray-900 `}>
        <Head>
          <title>Ke Dat</title>
          <meta name='description' content='Generated by create next app' />
          <link
            rel='icon'
            type='image/x-icon'
            href='https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Rave_Culture_Logo.jpg/220px-Rave_Culture_Logo.jpg'
          ></link>
        </Head>
        {/* body */}
        <main className=' dark:bg-gray-900'>
          <Facebook />
          <Banner />
          <Category />
          <Services />
          <MainCarousel />
          <Menu pizzas={pizzas} categories={categories} hamburgers={hamburgers} teas={teas} drinks={drinks} asianFoods={asianFoods} />
          <FAQ />
        </main>
      </div>
    </Layout>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const query = '*[_type=="pizza"]';
  const categoryQuery = '*[_type=="category"]';
  const hamburgerQuery = '*[_type=="hamburger"]';
  const teaQuery = '*[_type=="tea"]';
  const drinkQuery = '*[_type=="drink"]';
  const asianFoodQuery = '*[_type=="asianFood"]';
  const pizzas = await client.fetch(query);
  const categories = await client.fetch(categoryQuery);
  const hamburgers = await client.fetch(hamburgerQuery);
  const teas = await client.fetch(teaQuery);
  const drinks = await client.fetch(drinkQuery);
  const asianFoods = await client.fetch(asianFoodQuery);
  return {
    props: {
      pizzas,
      categories,
      hamburgers,
      teas,
      drinks,
      asianFoods,
    },
  };
};
